#!/bin/bash
#
# This program is free to use or modified
# at your ouwn risk
#
# writen by Guillermo Reisch (greisch@fing.edu.uy) and andrew (aaguirre@fing.edu.uy)
#


TURTLEARTVERSION=v114

export DIR=$(pwd | grep turtle_art_plugin)

if [ "$DIR" = "" ] ; then
    echo I dont know were Iam
    echo please execute this script inside the directory of the script
    exit
fi

# go to root of git
cd ..

# I want butiaXO folder be OK! (needed by plugin)
make -C butiaXO

# ok, lets inits and update the submodules (only works if you are in the root of git)
git submodule init
git submodule update
cd turtle_art_plugin

# goto mainline (Walter code) and check if all is OK!
cd mainline
git pull #make sure we have the last version of the git
export GITCONFIGURL=$(git config remote.origin.url | grep git://git.sugarlabs.org/turtleart/mainline.git )

if [ "$GITCONFIGURL" = "" ] ; then
    echo mmm... I dont know where is mainline git Walter repository
    exit
fi

# I want a especific version of TurtleArts!
git clean -xf
git reset
git checkout $TURTLEARTVERSION

#making folders and making all
cd ..
rm -rf tmp
cp -rL mainline tmp
rm -rf tmp/.git
cp -rLf butia tmp/plugins/
cp -rLf sumtia tmp/plugins/
cp -rLF ../followme_plugin/ tmp/plugins
cp -rLf stagin/* tmp/

#lets add localization
cat mainline/po/es.po butia/po/es.po > tmp/po/es.po

# ok, lest make this .xo
cd tmp
python setup.py fix_manifest
python setup.py dist_xo
cd ..
cp tmp/dist/*.xo .

#cleaning all
rm -rf tmp

# we finish
echo FINISH
