#!/bin/bash
#
# This program is free to use or modified
# at your ouwn risk
#
# writen by Guillermo Reisch (greisch@fing.edu.uy)
#


TURTLEARTVERSION=v108

export DIR=$(pwd | grep turtle_art_plugin)

if [ "$DIR" = "" ] ; then
    echo I dont know were Iam
    echo please execute this script inside the directory of the script
    exit
fi

# ok, lets inits and update the submodules
cd ../..
git submodule init
git submodule update
cd trunk/turtle_art_plugin

cd mainline
export GITCONFIGURL=$(git config remote.origin.url | grep git://git.sugarlabs.org/turtleart/mainline.git )

if [ "$GITCONFIGURL" = "" ] ; then
    echo mmm... I dont know where is mainline git Walter repository
    exit
fi

# I want a especific version!
git clean -xf
git reset
git checkout $TURTLEARTVERSION

#making folders and making all
cd ..
rm -rf tmp
cp -rL mainline tmp
rm -rf tmp/.git
cp -rLf butia tmp/plugins/
cp -rLf stagin/* tmp/

#lets add localization
cat mainline/po/es.po butia/po/es.po > tmp/po/es.po

# ok, lest make this .xo
cd tmp
python setup.py fix_manifest
python setup.py dist_xo
cd ..
cp tmp/dist/*.xo .

#cleaning all
rm -rf tmp

# we finish
echo FINISH
