####### Arduino simplification ######
#######
###############

ARDUINO_DIR  = /usr/share/arduino

TARGET       = CLItest

ARDUINO_LIBS = Wire

MCU          = atmega168

F_CPU        = 16000000

ARDUINO_PORT = /dev/cu.usb*

include Arduino.mk


