Document: turtlebots
Title: Debian turtlebots Manual
Author: <insert document author here>
Abstract: This manual describes what turtlebots is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/turtlebots/turtlebots.sgml.gz

Format: postscript
Files: /usr/share/doc/turtlebots/turtlebots.ps.gz

Format: text
Files: /usr/share/doc/turtlebots/turtlebots.text.gz

Format: HTML
Index: /usr/share/doc/turtlebots/html/index.html
Files: /usr/share/doc/turtlebots/html/*.html
